import Link from "next/link";
import { ArrowUpRight, Boxes, CreditCard, Network } from "lucide-react";
import { createPageMetadata } from "@/lib/seo";
import { divisions, sectors } from "@/lib/solutions";

export const metadata = createPageMetadata({ title: "SparkCraft Technologies | ICT, Fintech & Enterprise Solutions", description: "SparkCraft Technologies delivers ICT solutions, digital payment integration, and enterprise procurement in Dar es Salaam, Tanzania.", path: "" });

export default function Home() {
  return <main id="main-content">
    <section className="bg-[#071b30] text-white"><div className="container-wide grid min-h-[650px] items-center gap-12 py-20 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#e8bd5c]">ICT · Fintech · Enterprise Solutions</p><h1 className="mt-7 max-w-3xl text-[clamp(2.7rem,6vw,5.5rem)] font-black leading-[1.04] tracking-[-.055em]">Technology That Moves Your Business <span className="text-[#e8bd5c]">Forward.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/80">SparkCraft Technologies delivers integrated technology solutions, digital payment systems, and essential business supplies that help organizations work smarter and grow with confidence.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/services" className="corporate-button">Explore Our Solutions <ArrowUpRight size={18}/></Link><Link href="/contact" className="corporate-button-outline">Request a Quote</Link></div><p className="mt-12 text-sm text-white/55">Dar es Salaam, Tanzania · Serving businesses and institutions</p></div><div className="grid gap-4" aria-label="Our business divisions"><div className="rounded-xl border border-white/15 bg-white/5 p-7"><Network className="text-[#e8bd5c]" size={32}/><p className="mt-5 text-xs uppercase tracking-widest text-[#e8bd5c]">01 / Flagship</p><h2 className="mt-2 text-2xl font-bold">ICT Solutions</h2><p className="mt-2 text-white/65">Enterprise equipment, infrastructure, deployment, and support.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-white/15 bg-white/5 p-6"><CreditCard className="text-[#e8bd5c]"/><h2 className="mt-5 text-xl font-bold">Fintech & Payments</h2></div><div className="rounded-xl border border-white/15 bg-white/5 p-6"><Boxes className="text-[#e8bd5c]"/><h2 className="mt-5 text-xl font-bold">General Supplies</h2></div></div></div></div></section>
    <section className="corporate-section container-wide grid gap-10 lg:grid-cols-2"><div><p className="corporate-kicker">Your technology & business solutions partner</p><h2 className="corporate-title mt-4">The Right Technology. The Right Systems. The Right Support.</h2></div><div className="corporate-copy space-y-5"><p>Every organization needs reliable systems, efficient operations, and partners who understand its business requirements.</p><p>We bring together ICT equipment, digital technology, payment integration, and procurement capabilities. Whether you are equipping an office, connecting payment channels, or sourcing essential supplies, we coordinate the work from assessment to delivery and agreed support.</p></div></section>
    <section className="corporate-section bg-[#edf2f5]"><div className="container-wide"><p className="corporate-kicker">What we do</p><h2 className="corporate-title mt-4">Integrated Solutions for Modern Organizations</h2><p className="corporate-copy mt-5 max-w-3xl">From digital infrastructure to payment connectivity and essential supplies, our services are built around your operational requirements.</p><div className="mt-12 grid gap-5 md:grid-cols-3">{divisions.map(item => <article className="corporate-card flex flex-col" key={item.id}><span className="text-sm font-bold text-[#a47114]">{item.number} / Flagship</span><h3 className="mt-8 text-2xl font-bold text-[#071b30]">{item.name}</h3><p className="corporate-copy mt-4 flex-1">{item.short}</p><Link className="mt-8 inline-flex items-center gap-2 font-bold text-[#095579]" href={`/services#${item.id}`}>Explore service <ArrowUpRight size={18}/></Link></article>)}</div></div></section>
    <section className="corporate-section container-wide"><p className="corporate-kicker">The SparkCraft advantage</p><h2 className="corporate-title mt-4">More Than a Supplier. Your Technology Delivery Partner.</h2><div className="mt-12 grid gap-8 md:grid-cols-2 lg:grid-cols-4">{[["Built around your needs","Products and configurations aligned with your requirements, environment, and budget."],["Integrated capabilities","Hardware, software, payment connectivity, and procurement in one coordinated engagement."],["Partnership-led delivery","Working with clients, technology providers, and implementation partners toward agreed goals."],["Support beyond deployment","Installation, maintenance, troubleshooting, and technical support under agreed arrangements."]].map(([title, copy]) => <div className="border-t-4 border-[#d7aa45] pt-5" key={title}><h3 className="text-xl font-bold">{title}</h3><p className="corporate-copy mt-3">{copy}</p></div>)}</div></section>
    <section className="corporate-section bg-[#071b30] text-white"><div className="container-wide"><p className="corporate-kicker !text-[#e8bd5c]">Industries & sectors</p><h2 className="corporate-title mt-4">Technology for the Organizations That Keep Business Moving.</h2><div className="mt-12 grid gap-px overflow-hidden rounded-lg bg-white/20 md:grid-cols-2 lg:grid-cols-3">{sectors.map(([title, copy]) => <div className="bg-[#0c2943] p-7" key={title}><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-white/70">{copy}</p></div>)}</div></div></section>
    <section className="corporate-section container-wide"><p className="corporate-kicker">Our approach</p><h2 className="corporate-title mt-4">From Requirement to Reliable Delivery.</h2><div className="mt-12 grid gap-7 md:grid-cols-4">{[["Understand","We assess your objectives, environment, budget, and delivery expectations."],["Design & Source","We identify suitable products, configurations, and integration options."],["Deploy & Integrate","We coordinate supply, installation, testing, and handover."],["Support & Maintain","We provide agreed support and follow-up to help sustain performance."]].map(([title, copy], i) => <div key={title}><span className="text-4xl font-black text-[#b48931]">0{i+1}</span><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="corporate-copy mt-3">{copy}</p></div>)}</div></section>
    <section className="bg-[#d7aa45] py-16"><div className="container-wide flex flex-wrap items-center justify-between gap-7"><div><p className="text-sm font-bold uppercase tracking-widest">Let’s work together</p><h2 className="mt-2 text-3xl font-black text-[#071b30]">Have a Technology or Procurement Requirement?</h2><p className="mt-3 max-w-2xl text-[#253b4c]">Tell us what your organization needs and we’ll discuss an appropriate solution.</p></div><Link href="/contact" className="corporate-button !bg-[#071b30] !text-white">Request a Proposal <ArrowUpRight size={18}/></Link></div></section>
  </main>;
}
